### ISSUE TITLE
Cannot run code

### ISSUE THREAD

**Issue by afaideen** [Yalantis/OfficialFoldingTabBar.Android#1]
Can compile and program successfully. But when running I got this error from the log console,

Caused by: java.lang.RuntimeException: Font asset not found code_pro_lc.otf
                      at android.graphics.Typeface.createFromAsset(Typeface.java:190)
                      at client.yalantis.com.foldingtabbarandroid.CustomFontTextView.<init>(CustomFontTextView.java:30)
                      at client.yalantis.com.foldingtabbarandroid.CustomFontTextView.<init>(CustomFontTextView.java:0)
                      at java.lang.reflect.Constructor.newInstance(Native Method) 
                      at android.view.LayoutInflater.createView(LayoutInflater.java:619)

**Comment by root1991** [comment]
Fixed
