### ISSUE TITLE
Can't be used with Samsung Note 2 API 19

### ISSUE THREAD

**Issue by afaideen** [Yalantis/OfficialFoldingTabBar.Android#2]
Android console returned,
```
E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: client.yalantis.com.foldingtabbarandroid, PID: 26997
                  java.lang.NoClassDefFoundError: android.view.ViewAnimationUtils
                      at client.yalantis.com.foldingtabbarandroid.ProfileFragment.animateRevealColorFromCoordinates(ProfileFragment.java:48)
                      at client.yalantis.com.foldingtabbarandroid.ProfileFragment.access$000(ProfileFragment.java:20)
                      at client.yalantis.com.foldingtabbarandroid.ProfileFragment$1.onLayoutChange(ProfileFragment.java:39)
                      at android.view.View.layout(View.java:15771)
                      at android.view.ViewGroup.layout(ViewGroup.java:4867)
```

**Comment by root1991** [comment]
Fixed
