### ISSUE TITLE
Crash 

### ISSUE THREAD

**Issue by nitinkg7** [Yalantis/OfficialFoldingTabBar.Android#4]
App getting crashed after using the tabbar. Initialization is getting faliled.
E/UncaughtException: kotlin.UninitializedPropertyAccessException: lateinit property mData has not been initialized
                                                                            at client.yalantis.com.foldingtabbar.FoldingTabBar.initExpandAnimators(FoldingTabBar.kt:160)
                                                                            at client.yalantis.com.foldingtabbar.FoldingTabBar.access$initExpandAnimators(FoldingTabBar.kt:25)
                                                                            at client.yalantis.com.foldingtabbar.FoldingTabBar$initViewTreeObserver$1.onPreDraw(FoldingTabBar.kt:105)
                                                                            at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:944)
                                                                            at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2213)
                                                                            at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1258)
                                                                            at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6348)
                                                                            at android.view.Choreographer$CallbackRecord.run(Choreographer.java:871)
                                                                            at android.view.Choreographer.doCallbacks(Choreographer.java:683)
                                                                            at android.view.Choreographer.doFrame(Choreographer.java:619)
                                                                            at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:857)
                                                                            at android.os.Handler.handleCallback(Handler.java:751)
                                                                            at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                            at android.os.Looper.loop(Looper.java:154)
                                                                            at android.app.ActivityThread.main(ActivityThread.java:6123)
                                                                            at java.lang.reflect.Method.invoke(Native Method)
                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)

**Comment by root1991** [comment]
Could you please share more code?
